epithets = [
   "Sloppy",
   "Mini",
   "Ditzy",
   "Nervous",
   "Cryin'",
   "Lunatic",
   "Comrade",
   "Crooked",
   "Slow",
   "Sleepy",
   "Low Energy",
   "Crazy",
   "Lyin'",
   "Leakin'",
   "Shadey",
   "Slimeball",
   "Slippery",
   "Liddle'",
   "Meatball",
   "Wacky",
   "Little",
   "Goofy",
   "Low-IQ",
   "Deranged",
   "Weirdo",
   "Dumb as a Rock",
   "Lil'",
   "Psycho",
   "Dopey",
   "Fake News",
   "Low Ratings",
   "Failing",
   "Weak",
   "Corrupt",
   "Terrible",
   "Total Degenerate",
   "Crazed Warhawk",
   "Clown",
   "Disaster",
   "Dummy",
   "Disgraceful",
   "Biased",
   "Boring",
   "Incapable",
   "Dumb",
   "Incompetent",
   "Fascist",
   "Lowlife",
   "Horseface",
   "Truly Weird",
   "Sleazebag",
   "Perv Sleazebag",
   "Irrelevant",
   "Irrelevant Clown",
   "Broken Down",
   "Flunky"

   // "\"something\"" maybe add ability to check for surnames
]
// clown, disaster, dope, dummy, joke, liar.
/*
   absolute, zero, bad,
biased, boring, corrupt, crazy, crooked, disgraceful, disgusting, dumb, failed, failing, false, incapable,
incompetent, ine
*/
phrases = [
   "Despite the constant negative press covfefe",
   "[NAME] is so unlucky. Everything he touches turns into a mess. Some people just don't have it!",
   "[NAME] looks exhausted and beaten. He was never made or prepared for the job. Like it or not, he doesn't have \"it\"",
   // CHANGED TO .@[HANDLE]
   "[NAME] works really hard but is a guy who just doesn't have it - a total loser!",
   "[NAME] just doesn't have it. Time for a quarterback change!",
   "Wow, great news! I hear [NAME] was fired like a dog. If you read his tweets, you'll understand why. He just doesn't have IT!", //HANDLE
   "I hear that sleepy eyes [NAME] will be fired like a dog soon? I can't imagine what is taking so long!", // HANDLE
   "[NAME] just came to my office begging for money like a dog. Why doesn't he say that?", //HANDLE
   "Failed presidential candidate [NAME] should respect me. How nasty!",
   "[NAME]'s work was so bad that he has never been able to make a comeback. A third rate talent!",
   "The ultra liberal and seriously failing [NAME] is BEGGING my team for press credentials to my event in Iowa today-but they lie!",
   "[NAME] should be forced to take an IQ test before being allowed to talk to me.",
   "[NAME], who has lost all credibility with so many dumb statements and  picks, said last week that Kamala was in.",
   "[NAME] is a total clown. Has zero credibility!",
   "Really dumb [NAME]. Begged my people for a job. Turned him down twice and he went hostile. Major loser, zero credibility!",
   "[NAME] wouldn't know the truth if it hit him in the face.",
   "[NAME] is a total phony and dishonest guy.",
   "The only reason [NAME] doesn't like me is I refused to talk to him - asked many times. Very few care - sad!",
   //"I hear that [NAME], one of the dumber people in the world FINISH",
   "[NAME] sweats and shakes nervously as he talks \"bull\" about me. Has zero cred. Made fool of himself in '12.",
   "[NAME] is trying to act like a tough guy. Actually, he is weak, both mentally and physically!",
   //and yet he threatens me, for the second time, with physical assault. He doesn’t know me, but he would go down fast and hard, crying all the way. Don’t threaten people Joe!
   "[NAME] is now in the ring fighting against Trump.",
   "I know more about [NAME] than he knows about himself.",
   "Has anyone seen the financials of [NAME]. He is doing really badly. Too much debt. Need money fast. Funny!",
   "All [NAME] does is go on television and talk, talk, talk, but incapable of doing anything.",
   "Why would anybody listen to [NAME]?",
   "[NAME] should have gone to prison.",
   "[NAME] was easy for me to beat.",
   "[NAME] who knows nothing about me is commenting all over T.V. and the media as though he has great D.J.T. insight. Knows NOTHING!",
   "Wow, [NAME] is really dumb. People are going wild on twitter! Funny to watch.",
   "[NAME] you should be ashamed of yourself.",
   "I just realized that if you listen to [NAME] for more than ten minutes straight, you develop a massive headache. He has zero chance!",
   "Enough is Enough- no more [NAME]!",
   "[NAME] reminds me of a spoiled brat without a properly functioning brain.",
   "[NAME] must have had a terrible vacation, he is really off his game.",
   "[NAME] is angry and obnoxious, he will never make it on T.V.",
   "I truly understood the appeal of his father, but [NAME] didn't get the right gene.",
   "[NAME] asked me for $1 million. I said no.",
   "[NAME] has been confused for forty years.",
   "[NAME] is truly one of the dumbest of the talking heads - he doesn't have a clue!",
   "Do you ever notice that [NAME] constantly goes after me but when I hit back it is totally rude. He is highly overrated!",
   "I think [NAME] should take another eleven day \"unscheduled\" vacation.",
   "[NAME] lost it tonight.",
   "The incompetence of [NAME] is beyond comprehension.",
   "I wonder why somebody doesn't do something about [NAME] and his totally dishonest words.",
   "[NAME] has no power, but so dishonest!",
   "I hear [NAME] is in big trouble.",
   "[NAME] is a total low life--- read his past tweets. A dummy with no “it” factor. Will fade fast.",
   "[NAME] said CLIMATE CHANGE is the most important thing, not all of the current disasters! ",
   "[NAME] is looking to give big dollars to Lyin' Kamal because he feels he can mold her into his perfect little puppet. I agree!",
   "Can anyone imagine [NAME] as president? No way.",
   "[NAME] is a biased dope who talked falsely about me re China.",
   "I, along with almost everyone else, have so little confidence in [NAME]",
   "[NAME] is being severely criticized for being incapable of understanding anything.",
   "[NAME], who is wrong almost all of the time, should be thrown off twitter. Boring and totally biased!",
   "[NAME], a big proponent of the Iraq War and other catastrophes, doesn't like me very much. That means I win!",
   "[NAME] should focus his special interest money on building up his failed image.",
   "[NAME] isn't smart enough to know what is going on here.",
   "I can easily beat [NAME]. HE HAS NO STRENGTH OR STAMINA, both of which are needed to MAKE AMERICA GREAT AGAIN!",
   "The virtually incompetent [NAME], who has had a failed career, is incoherent with anger at me!",
   "[NAME] doesn't have what it takes",
   "[NAME] does not have the STRENGTH or STAMINA to be President.",
   "Weak and totally conflicted people like [NAME] shouldn't be allowed on twitter",
   "[NAME] continues to make and write false statements.",
   "[NAME] just doesn't know about winning!",
   "[NAME] is a nice guy , but just hopeless. He knows so little about politics and, in particular, winning!"
]